a=11;
b=17;
c=a+b;
print("enter the vlaue :",c);
d=a-b;
print("enter the vlaue :",d);
e=a/b;
print("enter the float value:",e);
print("Increment values:",(a+1));
print("decrement values:",(b-1));
f=c/d;
print("modules values",f);